<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Imagekit" Version="6.1.0" />
    <PackageReference Include="Mapster" Version="10.0.10" />
    <PackageReference Include="Mapster.Async" Version="10.0.10" />
    <PackageReference Include="Mapster.Core" Version="10.0.10" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Mapster.EFCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.19.1" />
    <PackageReference Include="SkiaSharp" Version="4.148.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.148.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FitnessTracker.Entities\FitnessTracker.Entities.csproj" />
    <ProjectReference Include="..\FitnessTracker.Shared\FitnessTracker.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
  </ItemGroup>

</Project>
